### ISSUE TITLE
zigmod support

### ISSUE THREAD

**Issue by locriacyber** [JonSnowbd/ZT#12]
The current `zig.mod` is just wrong. It should point to `src/main.zig` and include C dependencies.

Documentation of `zig.mod`: https://github.com/nektro/zigmod/blob/master/docs/zig.mod.md

**Comment by JonSnowbd** [comment]
This is a choice based on my talks with Nektro. Due to the C deps being many and changing depending on the platform, zigmod targeting the build is the best choice for ease of development. I personally do not use any of the zig package managers so I do not follow their development closely. If c file management has been significantly changed I'm more than willing to update it.
