### ISSUE TITLE
Endless errors

### ISSUE THREAD

**Issue by jeffbdavenport** [JonSnowbd/ZT#29]
After spending 2 hours trying to get this to run on both zig 0.11 and zig 0.10.1, there are endless amount of errors trying to get it to compile. I have given up

**Comment by JonSnowbd** [comment]
Hi, sorry about that, I've been putting off updating my Zig libraries until the official Zig Package Manager was good enough to support how ZT is built, so the user installation is simply using `b.InstallPackage(url)`. Besides the lack of updates in this regard, Zig has also been going through breaking changes I have not kept up on. I'll look at the ZPM now and see if I can start, but otherwise I'll be closing this issue and I'll hit you up with a reply here, that it is updated, if you still want to use the library.

In the meantime I can recommend [zig-gamedev](https://github.com/michal-z/zig-gamedev) as a good alternative

**Comment by jeffbdavenport** [comment]
Fair enough, I've just been trying to get a docking branch to work with zig for imgui for several weeks now, haven't made any progress. Seems it is just not possible
