### ISSUE TITLE
cimplot/cimnodes integration

### ISSUE THREAD

**Issue by Jack-Ji** [JonSnowbd/ZT#7]
Hi @JonSnowbd, great work recently! 
As a graphics application framework, ZT's gui parts could be greatly enhanced by integrating other imgui extension libraries, specifically [cimplot](https://github.com/cimgui/cimplot) and [cimnodes](https://github.com/cimgui/cimnodes), which are very useful when writing handy tools.

[DearPyGui](https://github.com/hoffstadt/DearPyGui) is a good example of this, however, python isn't so great for building really heavy stuff (and not so fun to write in my opinion), you get the point :-).

**Comment by JonSnowbd** [comment]
I'd like to use some of these libraries so I'm on board with adding it, but they could prove annoying to port properly. I'll look into providing these through build.zig rather than throwing them in with every dist of ZT. It might take me a bit to get to this as I'm working on a game engine to complement ZT.
